- id: check-file-names
  name: Check file names
  description: Check that file names follow naming conventions
  entry: src/file_name_checker.py
  language: python
  files: .*
  exclude: ^(\.git/|__pycache__/|\.pytest_cache/|node_modules/)
  pass_filenames: true

- id: check-directory-names
  name: Check directory names
  description: Check that directory names follow naming conventions
  entry: src/directory_checker.py
  language: python
  files: .*
  exclude: ^(\.git/|__pycache__/|\.pytest_cache/|node_modules/)
  pass_filenames: false
  always_run: true
