- id: check-file-names
  name: check file names
  description: Check that file names follow naming conventions
  entry: filename-linter
  language: python
  files: .*
  exclude: ^(\.git/|__pycache__/|\.pytest_cache/|node_modules/)
  pass_filenames: true

- id: check-directory-names
  name: check directory names
  description: Check that directory names follow naming conventions
  entry: directory-linter
  language: python
  files: .*
  exclude: ^(\.git/|__pycache__/|\.pytest_cache/|node_modules/)
  pass_filenames: false
  always_run: true

- id: check-empty-files
  name: check empty files
  description: Check for empty files that shouldn't be committed
  entry: empty-file-linter
  language: python
  files: .*
  exclude: ^(\.git/|__pycache__/|\.pytest_cache/|node_modules/)
  pass_filenames: false
  always_run: true

- id: check-duplicate-files
  name: check duplicate files
  description: Check for files with identical content
  entry: duplicate-file-linter
  language: python
  files: .*
  exclude: ^(\.git/|__pycache__/|\.pytest_cache/|node_modules/)
  pass_filenames: false
  always_run: true
